### ISSUE TITLE
Drawing a sprite inside a hexagonal grid cell.

### ISSUE THREAD

**Issue by skarmux** [skarmux/settlers-neo#2]
The sprite bottom center should match the grid cell center.

**Comment by tehKaiN** [comment]
in godot, everything is a scene, including reusable saved object hierarchies, called prefabs in unity.

1. create a scene with node2d being its top level node
2. add sprite inside and position it however you like in relation to top level node's center point
3. then, each time you instantiate and reposition the settler scene prefab, set it's global_position to grid tile's center position.

you can use stress_test's settler.tscn as a point of reference.
